server :
  address : 0.0.0.0
  port: 8080

service :
  ribbon :
    listOfServers: http://localhost:3000
    
ui :
  ribbon :
    listOfServers: http://www.google.com
    
zuul:
  retryable: false
  routes:
    service :
      path : /service/**
    ui :
      path : /ui/**

saml:
  sso:
    metadata-generator:
      entity-id: localhost-demo 
    key-manager:
      private-key-der-location: classpath:/localhost.key.der
      public-key-pem-location: classpath:/localhost.cert
    idp:
      metadata-location: classpath:/idp-okta.xml

       